### ISSUE TITLE
Include ETA in progressbar

### ISSUE THREAD

**Issue by pykong** [goblinfactory/konsole#19]
It would be really great if the progress bar could be configured to show the estimated time of completion.
Such could be easily interpolated by averaging the time needed per iteration.
That would be highly informative!

**Comment by goblinfactory** [comment]
back in the day we used to call those "microsoft minutes" :)
I can see too many scenarios where the calculated time would be significantly out, 
Nothing stopping you from adding that in yourself into the text.
I will leave this open for a short while for you to reply.
cheers, 
Alan
