### ISSUE TITLE
crash on Writeline of Json

### ISSUE THREAD

**Issue by eiredrake** [goblinfactory/konsole#29]
This is a really odd one. 

Using the same plumbing as before, the log emit is trying to output a log entry containing some well formatted JSON. The call to .WriteLine() throws a FormatException..... the kind of thing you'd see if you were passing a formatting string and some parameters... but all I'm doing is passing a string.

The Logging_Console variable below is held in a class injected as a singleton. It is a Konsole.IConsole initialized as  logging_console = Window.Open(0, progress_window_height, main_window_width, main_window_height - progress_console.WindowHeight - command_console.WindowHeight - (window_padding * 2), "operation logging", Konsole.Drawing.LineThickNess.Single);

Log entry:
`"SessionId: -1 receiving json "{\"code\":3837,\"sessionId\":-1,\"payload\":{\"text\":\"client requesting session id\"}}"`

```
public void Emit(LogEvent logEvent)
{
   Dawn.Guard.Argument(() => logEvent).NotNull();
   var message = logEvent.RenderMessage(_formatProvider);
   this.consoleWrapper.Logging_Console.WriteLine(message); // <--- exception
}
```

```
Exception:  {"Input string was not in a correct format."} | System.FormatException

stack trace:
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Konsole.Window.Write(String format, Object[] args)
   at Konsole.Window.WriteLine(String format, Object[] args)
   at Konsole.ConcurrentWriter.WriteLine(String format, Object[] args)
   at consoleTools.Implementations.Serilog_Sink.StealthConsoleSink.Emit(LogEvent logEvent) in C:\Users\ekramer\Documents\Visual Studio 2019\Projects\consoleTools\consoleTools\Implementations\Serilog_Sink\StealthConsoleSink.cs:line 33
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
```

Since a params object[] parameter accepts  'nothing' as an argument it is compiling. But when it gets down to Window.cs line 457-ish the call to string.format(format, args) is for some reason interpretting my json string as a formatted string with no arguments provided and is choking on it.

Edit: hrm.. this is odd too... a quick test of the Json string with string.Format()

                var bar = string.Format("SessionId: -1 receiving json {\"code\":3837,\"sessionId\":-1,\"payload\":{\"text\":\"client requesting session id\"}}");

the linter in Vs2019 is showing that line underlined green with a message of 'format string contains an invalid place holder'

wonder if i need to somehow sanitize it before passing it in?

**Comment by eiredrake** [comment]
ok a quick bit of googlefu reveals some goofiness on C#'s part not your code

according to this: [(https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting?redirectedfrom=MSDN)]

as found from here [https://stackoverflow.com/questions/14573650/string-format-input-string-was-not-in-a-correct-format]

the string.format() method is interpreting the single curly braces in the Json as format placeholders.

If I modify the string like this:

`var bar = string.Format("SessionId: -1 receiving json {{\"code\":3837,\"sessionId\":-1,\"payload\":{{\"text\":\"client requesting session id\"}}");`

then string.format takes it just fine. Note the doubled {{. Escaping them doesn't work you have to escape using another {. 

That's just silly.

**Comment by goblinfactory** [comment]
:D
glad you're sorted. closing this now.
