### ISSUE TITLE
window area borders disappeared

### ISSUE THREAD

**Issue by eiredrake** [goblinfactory/konsole#34]
I'm not sure exactly what's going on but I have a very long process that I've been working to parallelize. It does take quite a bit of  resource so that might be part of it. Anyway the borders between the various areas on the console window have disappeared. Everything appears to be working. Like the progress bar is still updating and the scrolling log window is still scrolling. So it doesn't appear to be hurting anything.

I don't know if it matters or not but I'm currently using a second progress bar in the first panel as a stationary label to display the current run time.  It's being updated in the second level of a paralellized nested loop

![borders_present](https://user-images.githubusercontent.com/10224957/70356318-2112a680-1842-11ea-9f13-a0c22367a918.png)
![missing_borders](https://user-images.githubusercontent.com/10224957/70356324-240d9700-1842-11ea-850c-b66c184f63a4.png)

**Comment by goblinfactory** [comment]
you have some code or process somewhere that has continue to write to standard out (the main console) and that has scrolled off the screen resulting in only the "window portions that get updated from remaining. 

To fix this, stop the other processes from writing to the console, I will create a backlog feature item to add a means to redirect standard out to console window, so you can create a new window section to render any system or process output. 
So, for now... track down what process is writing to the console and pass that process the necessary command arguments to be 'quiet' (quiet mode) etc.

**Comment by goblinfactory** [comment]
If you still think this might be a bug with Konsole, (which it doesnt look like though), you'll need to please first debug your application, and work out what the actual bug is, then submit a small bit of code that demonstrates the bug, and submit that with your issue. Thank you. A
